# project
## Name: Zainab fuzail
## Roll No: BSAIM-F24-133

<div class="alert alert-block alert-warning">

<b> Data Load </b>
</div>

import libraries

In [20]:


import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [21]:
import numpy as np

<div class="alert alert-block alert-warning">

<b> Data gathering</b>
</div>

In [22]:
df = pd.read_csv("2018-2019_Daily_Attendance_20240429.csv")
df

       School DBN      Date  Enrolled  Absent  Present  Released
0          01M015  20180905       172      19      153         0
1          01M015  20180906       171      17      154         0
2          01M015  20180907       172      14      158         0
3          01M015  20180912       173       7      166         0
4          01M015  20180913       173       9      164         0
...           ...       ...       ...     ...      ...       ...
277148     79X695  20190620       230      46      136        48
277149     79X695  20190621       226      53      128        45
277150     79X695  20190624       226      42      130        54
277151     79X695  20190625       226      56      127        43
277152     79X695  20190626       216      27       68       121

[277153 rows x 6 columns]

<div class="alert alert-block alert-warning">

<b> Data Peprocessing</b>
</div>

In [23]:
df.head()

  School DBN      Date  Enrolled  Absent  Present  Released
0     01M015  20180905       172      19      153         0
1     01M015  20180906       171      17      154         0
2     01M015  20180907       172      14      158         0
3     01M015  20180912       173       7      166         0
4     01M015  20180913       173       9      164         0

In [24]:
df.tail()

       School DBN      Date  Enrolled  Absent  Present  Released
277148     79X695  20190620       230      46      136        48
277149     79X695  20190621       226      53      128        45
277150     79X695  20190624       226      42      130        54
277151     79X695  20190625       226      56      127        43
277152     79X695  20190626       216      27       68       121

In [25]:
df.describe()

               Date      Enrolled         Absent        Present       Released
count  2.771530e+05  277153.00000  277153.000000  277153.000000  277153.000000
mean   2.018665e+07     596.98617      50.503538     544.499403       1.983229
std    4.555413e+03     482.90966      54.329671     452.970313      35.114511
min    2.018090e+07       1.00000       0.000000       1.000000       0.000000
25%    2.018111e+07     329.00000      23.000000     291.000000       0.000000
50%    2.019013e+07     476.00000      38.000000     430.000000       0.000000
75%    2.019041e+07     684.00000      59.000000     640.000000       0.000000
max    2.019063e+07    5955.00000    2151.000000    5847.000000    5904.000000

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277153 entries, 0 to 277152
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   School DBN  277153 non-null  object
 1   Date        277153 non-null  int64
 2   Enrolled    277153 non-null  int64
 3   Absent      277153 non-null  int64
 4   Present     277153 non-null  int64
 5   Released    277153 non-null  int64
dtypes: int64(5), object(1)
memory usage: 12.7+ MB

In [27]:
df.dtypes

School DBN    object
Date           int64
Enrolled       int64
Absent         int64
Present        int64
Released       int64
dtype: object

In [28]:
df['School DBN'].unique()

array(['01M015', '01M019', '01M020', ..., '79M331', '79Q344', '79X695'],
      dtype=object)

In [29]:
df['Enrolled'].nunique()

3102

In [30]:
df.columns

Index(['School DBN', 'Date', 'Enrolled', 'Absent', 'Present', 'Released'], dtype='object')

In [31]:
df.isnull()

        School DBN   Date  Enrolled  Absent  Present  Released
0            False  False     False   False    False     False
1            False  False     False   False    False     False
2            False  False     False   False    False     False
3            False  False     False   False    False     False
4            False  False     False   False    False     False
...            ...    ...       ...     ...      ...       ...
277148       False  False     False   False    False     False
277149       False  False     False   False    False     False
277150       False  False     False   False    False     False
277151       False  False     False   False    False     False
277152       False  False     False   False    False     False

[277153 rows x 6 columns]

In [32]:
df.isnull().sum()

School DBN    0
Date          0
Enrolled      0
Absent        0
Present       0
Released      0
dtype: int64

In [33]:
print(f" rows {df.shape[0]}")
print(f" column {df.shape[1]}")

 rows 277153
 column 6

In [34]:
df.dtypes

School DBN    object
Date           int64
Enrolled       int64
Absent         int64
Present        int64
Released       int64
dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277153 entries, 0 to 277152
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   School DBN  277153 non-null  object
 1   Date        277153 non-null  int64
 2   Enrolled    277153 non-null  int64
 3   Absent      277153 non-null  int64
 4   Present     277153 non-null  int64
 5   Released    277153 non-null  int64
dtypes: int64(5), object(1)
memory usage: 12.7+ MB

In [36]:
df.head()

  School DBN      Date  Enrolled  Absent  Present  Released
0     01M015  20180905       172      19      153         0
1     01M015  20180906       171      17      154         0
2     01M015  20180907       172      14      158         0
3     01M015  20180912       173       7      166         0
4     01M015  20180913       173       9      164         0

In [37]:
df.dtypes

School DBN    object
Date           int64
Enrolled       int64
Absent         int64
Present        int64
Released       int64
dtype: object

In [38]:
def convertObjToInt(cols):
    for i in cols:
        data = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(data))    # data_LE.fit(data)
        df[i] = data_LE.transform(df[i])
        
columns = ['School DBN']
convertObjToInt(columns)

In [39]:
df.drop("Released", axis=1, inplace=True)

In [40]:
df.dtypes

School DBN    int32
Date          int64
Enrolled      int64
Absent        int64
Present       int64
dtype: object

In [41]:
X = df.drop('Present', axis=1)   # Dependant columns / Input columns
y = df['Present']                # Resultant columns / Output column